### ISSUE TITLE
ImageMagick vs GraphicsMagick

### ISSUE THREAD

**Issue by dhuf** [nitsan-technologies/ns_t3_chk_server_compatibility#2]
Currently on v8 we are using GraphicsMagick, would be good to test it also I think

**Comment by nitsan-technologies** [comment]
Dear @dhuf 

Thank you very much for your suggestions. We really appreciate your input on this.

We have now also added the GraphicsMagick in the checklist. Please see this screenshot: 
![ns_compatibility_graphics_image](https://user-images.githubusercontent.com/2622317/41293977-7d75efd2-6e74-11e8-9794-193eebe2d984.png)

Please let's know if you have any other suggestion so we can improve this and can help to the community.

Regards.

**Comment by dhuf** [comment]
Perfect, thank you. I'll do it if I see anything.
